<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>1cc</string>
	</array>
	<key>name</key>
	<string>One Command</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^[ \t]*#.*$</string>
			<key>name</key>
			<string>comment.line.number-sign.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\[ \t]*$</string>
			<key>name</key>
			<string>comment.other.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\\;</string>
			<key>name</key>
			<string>comment.other.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z0-9_]+\b(?!\()</string>
			<key>name</key>
			<string>storage.type.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|\$[a-zA-Z0-9_]+\b\|</string>
			<key>name</key>
			<string>storage.type.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\$[a-zA-Z0-9_]+\b(?=\()</string>
			<key>name</key>
			<string>entity.name.function.one_command</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(?&lt;=INIT:|COND:|REPEAT:)\s*(COND|INIT|REPEAT):</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^\s*(COND|INIT|REPEAT):</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*(?:(?:INIT:|COND:|REPEAT:)[ \t]*)*?(INIT):[ 	]*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*(?:(?:INIT:|COND:|REPEAT:)[ \t]*)*?(COND):[ 	]*</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.one_command</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*(DEFINE):[ \t]*([a-zA-Z0-9_]+(?!\()\b)?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.modifier.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*(UNDEFINE):[ \t]*[a-zA-Z0-9_]+\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)(?&lt;=INIT:|COND:|REPEAT:)[ \t]*(BLOCK):[ \t]*[a-zA-Z0-9_:]+(:\d{1,2})?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*(BLOCK):[ \t]*[a-zA-Z0-9_:]+(:\d{1,2})?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.one_command</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.one_command</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.one_command</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*(FOR)[ \t]*\((?:([a-zA-Z0-9_]+);)?(-?\d+(?:\.\d+)?)(?:,(-?\d+(?:\.\d+)?))?(?:,(-?\d+(?:\.\d+)?))?\):[ \t]*$</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9_]+)\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.one_command</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([a-zA-Z0-9_]+)</string>
					<key>name</key>
					<string>variable.parameter.one_command</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>([a-zA-Z0-9_]+)=(!)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.one_command</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?![a-zA-Z_\|\$])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\|[a-zA-Z0-9_]*\|</string>
					<key>name</key>
					<string>variable.parameter.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\$?[a-zA-Z0-9_]*\|</string>
					<key>name</key>
					<string>storage.type.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[a-zA-Z_]</string>
					<key>name</key>
					<string>string.unquoted.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\d+)</string>
					<key>name</key>
					<string>constant.numeric.one_command</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.one_command</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)^[ \t]*:(ENDFOR)[ \t]*$</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~|-?\d*(?:\d[bsl]?|\.\d+[fd]?)</string>
			<key>name</key>
			<string>constant.numeric.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>@[prae]</string>
			<key>name</key>
			<string>storage.type.one_command</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\\\\)*"</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.one_command</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?:(?&lt;!\\)(\\\\)*")|((?&lt;!\\)\n)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.character.one_command</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.one_command</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.one_command</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>~|-?\d*(?:\d[bsl]?|\.\d+[fd]?)</string>
					<key>name</key>
					<string>constant.numeric.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|[a-zA-Z0-9_]*\|</string>
					<key>name</key>
					<string>variable.parameter.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|\$?[a-zA-Z0-9_]*\|</string>
					<key>name</key>
					<string>storage.type.one_command</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[ \t]*
</string>
					<key>name</key>
					<string>comment.other.one_command</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>§[\da-fA-Fk-oK-OrR]?</string>
			<key>name</key>
			<string>invalid.illegal.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>false|true</string>
			<key>name</key>
			<string>constant.language.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>minecraft:</string>
			<key>name</key>
			<string>constant.language.one_command</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\|[a-zA-Z0-9_]*\|</string>
			<key>name</key>
			<string>variable.parameter.one_command</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.one_command</string>
	<key>uuid</key>
	<string>cabd43d7-cf20-4530-8822-b50016a67fe8</string>
</dict>
</plist>
